// Generated by scripts/figma/build.py — do not edit.
export type FigmaImage = { src: string; w: number; h: number; fit: 'cover' | 'contain' | 'fill'; box?: number[]; aspect?: number }

export const images = {
  "value-innovation": {
    "src": "/figma/img/value-innovation.webp",
    "w": 282,
    "h": 282,
    "fit": "cover"
  },
  "value-reliability": {
    "src": "/figma/img/value-reliability.webp",
    "w": 311,
    "h": 311,
    "fit": "cover"
  },
  "value-flexibility": {
    "src": "/figma/img/value-flexibility.webp",
    "w": 317,
    "h": 317,
    "fit": "cover"
  },
  "service-phone": {
    "src": "/figma/img/service-phone.webp",
    "w": 696.255,
    "h": 1044.382,
    "fit": "cover"
  },
  "service-card": {
    "src": "/figma/img/service-card.webp",
    "w": 728,
    "h": 728,
    "fit": "cover"
  },
  "service-api": {
    "src": "/figma/img/service-api.webp",
    "w": 828.463,
    "h": 1012.106,
    "fit": "cover"
  },
  "app-biznes": {
    "src": "/figma/img/app-biznes.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-credit": {
    "src": "/figma/img/app-credit.webp",
    "w": 140,
    "h": 140,
    "fit": "fill"
  },
  "app-superapp": {
    "src": "/figma/img/app-superapp.webp",
    "w": 140,
    "h": 140,
    "fit": "fill"
  },
  "app-smile": {
    "src": "/figma/img/app-smile.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-ailab": {
    "src": "/figma/img/app-ailab.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-findiag": {
    "src": "/figma/img/app-findiag.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-aicall": {
    "src": "/figma/img/app-aicall.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-voicepay": {
    "src": "/figma/img/app-voicepay.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-buyurtmam": {
    "src": "/figma/img/app-buyurtmam.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-biznesim": {
    "src": "/figma/img/app-biznesim.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-crm": {
    "src": "/figma/img/app-crm.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-hrm": {
    "src": "/figma/img/app-hrm.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-edo": {
    "src": "/figma/img/app-edo.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "app-dev": {
    "src": "/figma/img/app-dev.webp",
    "w": 180,
    "h": 179,
    "fit": "fill"
  },
  "app-audit": {
    "src": "/figma/img/app-audit.webp",
    "w": 180,
    "h": 180,
    "fit": "fill"
  },
  "app-consulting": {
    "src": "/figma/img/app-consulting.webp",
    "w": 180,
    "h": 180,
    "fit": "fill"
  },
  "feature-superapp": {
    "src": "/figma/img/feature-superapp.webp",
    "w": 140,
    "h": 140,
    "fit": "fill"
  },
  "feature-biometric": {
    "src": "/figma/img/feature-biometric.webp",
    "w": 140,
    "h": 140,
    "fit": "fill"
  },
  "feature-internship": {
    "src": "/figma/img/feature-internship.webp",
    "w": 140,
    "h": 140,
    "fit": "cover"
  },
  "ai-visual": {
    "src": "/figma/img/ai-visual.webp",
    "w": 1500,
    "h": 1444,
    "fit": "cover"
  },
  "outsourcing-visual": {
    "src": "/figma/img/outsourcing-visual.webp",
    "w": 1475.257,
    "h": 1049,
    "fit": "cover"
  },
  "b2b-visual": {
    "src": "/figma/img/b2b-visual.webp",
    "w": 1536,
    "h": 1024,
    "fit": "cover"
  },
  "qr": {
    "src": "/figma/img/qr.webp",
    "w": 304,
    "h": 288,
    "fit": "fill"
  },
  "partner-local-1": {
    "src": "/figma/img/partner-local-1.webp",
    "w": 278.459,
    "h": 268.667,
    "fit": "cover",
    "box": [
      24.62,
      -7.987,
      50.606,
      116.812
    ],
    "aspect": 2.392
  },
  "partner-local-2": {
    "src": "/figma/img/partner-local-2.webp",
    "w": 259,
    "h": 250,
    "fit": "cover",
    "box": [
      26.455,
      -3.913,
      47.07,
      108.696
    ],
    "aspect": 2.392
  },
  "partner-local-3": {
    "src": "/figma/img/partner-local-3.webp",
    "w": 295,
    "h": 162,
    "fit": "cover",
    "box": [
      24.561,
      16.957,
      53.612,
      70.435
    ],
    "aspect": 2.392
  },
  "partner-local-4": {
    "src": "/figma/img/partner-local-4.webp",
    "w": 423.4,
    "h": 116,
    "fit": "cover",
    "box": [
      11.313,
      24.783,
      76.947,
      50.435
    ],
    "aspect": 2.392
  },
  "partner-local-5": {
    "src": "/figma/img/partner-local-5.webp",
    "w": 351,
    "h": 338,
    "fit": "cover",
    "box": [
      17.992,
      -23.043,
      63.789,
      146.957
    ],
    "aspect": 2.392
  },
  "partner-local-6": {
    "src": "/figma/img/partner-local-6.webp",
    "w": 270,
    "h": 90,
    "fit": "fill",
    "box": [
      25.365,
      30.87,
      49.069,
      39.13
    ],
    "aspect": 2.392
  },
  "partner-local-7": {
    "src": "/figma/img/partner-local-7.webp",
    "w": 230.244,
    "h": 222.148,
    "fit": "cover",
    "box": [
      29.002,
      2.126,
      41.844,
      96.586
    ],
    "aspect": 2.392
  },
  "partner-local-8": {
    "src": "/figma/img/partner-local-8.webp",
    "w": 399.614,
    "h": 323.73,
    "fit": "fill",
    "box": [
      14.305,
      -22.609,
      72.624,
      140.752
    ],
    "aspect": 2.392
  },
  "partner-intl-1": {
    "src": "/figma/img/partner-intl-1.webp",
    "w": 335.901,
    "h": 203.98,
    "fit": "cover",
    "box": [
      -4.535,
      6.989,
      109.414,
      88.687
    ],
    "aspect": 1.335
  },
  "partner-intl-2": {
    "src": "/figma/img/partner-intl-2.webp",
    "w": 324,
    "h": 196,
    "fit": "cover",
    "box": [
      -2.606,
      10.87,
      105.537,
      85.217
    ],
    "aspect": 1.335
  },
  "partner-intl-3": {
    "src": "/figma/img/partner-intl-3.webp",
    "w": 292,
    "h": 178,
    "fit": "cover",
    "box": [
      2.606,
      12.609,
      95.114,
      77.391
    ],
    "aspect": 1.335
  },
  "partner-intl-4": {
    "src": "/figma/img/partner-intl-4.webp",
    "w": 349.037,
    "h": 349.037,
    "fit": "cover",
    "box": [
      -6.674,
      -24.545,
      113.693,
      151.755
    ],
    "aspect": 1.335
  },
  "partner-intl-5": {
    "src": "/figma/img/partner-intl-5.webp",
    "w": 266,
    "h": 81,
    "fit": "cover",
    "box": [
      6.84,
      29.565,
      86.645,
      35.217
    ],
    "aspect": 1.335
  },
  "partner-intl-6": {
    "src": "/figma/img/partner-intl-6.webp",
    "w": 286,
    "h": 174,
    "fit": "cover",
    "box": [
      3.583,
      13.478,
      93.16,
      75.652
    ],
    "aspect": 1.335
  },
  "cert-1": {
    "src": "/figma/img/cert-1.webp",
    "w": 261.78,
    "h": 268.324,
    "fit": "contain"
  },
  "cert-2": {
    "src": "/figma/img/cert-2.webp",
    "w": 261.778,
    "h": 268.322,
    "fit": "contain"
  },
  "cert-3": {
    "src": "/figma/img/cert-3.webp",
    "w": 352.429,
    "h": 219.761,
    "fit": "contain"
  },
  "cert-4": {
    "src": "/figma/img/cert-4.webp",
    "w": 451.851,
    "h": 155.537,
    "fit": "contain"
  }
} as const satisfies Record<string, FigmaImage>

export const groups = {
  "partnersLocal": [
    "partner-local-1",
    "partner-local-2",
    "partner-local-3",
    "partner-local-4",
    "partner-local-5",
    "partner-local-6",
    "partner-local-7",
    "partner-local-8"
  ],
  "partnersIntl": [
    "partner-intl-1",
    "partner-intl-2",
    "partner-intl-3",
    "partner-intl-4",
    "partner-intl-5",
    "partner-intl-6"
  ],
  "certs": [
    "cert-1",
    "cert-2",
    "cert-3",
    "cert-4"
  ]
} as const
